<?
 
$table="sysvar";

 
$sql="

CREATE TABLE IF NOT EXISTS `".$cid."sysreportdesign` (
  `report_group` varchar(50) character set utf8 default NULL,
  `sequence` int(11) default NULL,
  `description` varchar(255) character set utf8 default NULL,
  `formulas` varchar(255) character set utf8 default NULL,
  `debitorcredit` varchar(50) character set utf8 default NULL,
  `plusorminus` varchar(50) character set utf8 default NULL,
  `fonttype` varchar(50) character set utf8 default NULL,
  `colvalue1` double default NULL,
  `colvalue2` double default NULL,
  `colvalue3` double default NULL,
  `colvalue4` double default NULL,
  `id` int(11) NOT NULL auto_increment,
  `sourceautonumber` varchar(50) character set utf8 default NULL,
  `sourcefile` varchar(255) character set utf8 default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
";
if($link->query($sql))echo mysqli_error($link);
$sql="

CREATE TABLE IF NOT EXISTS `".$cid."sysreportdesignfiles` (
  `filename` varchar(50) character set utf8 NOT NULL,
  `report_group` varchar(50) character set utf8 default NULL,
  `sequence` int(11) default NULL,
  `description` varchar(255) character set utf8 default NULL,
  `formulas` varchar(255) character set utf8 default NULL,
  `debitorcredit` varchar(50) character set utf8 default NULL,
  `plusorminus` varchar(50) character set utf8 default NULL,
  `fonttype` varchar(50) character set utf8 default NULL,
  `colvalue1` double default NULL,
  `colvalue2` double default NULL,
  `colvalue3` double default NULL,
  `colvalue4` double default NULL,
  `id` int(11) NOT NULL auto_increment,
  `sourceautonumber` varchar(50) character set utf8 default NULL,
  `sourcefile` varchar(255) character set utf8 default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `x1` (`filename`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
";
if($link->query($sql))echo mysqli_error($link);
$sql="

CREATE TABLE IF NOT EXISTS `".$cid."system_variables` (
  `varname` varchar(50) character set utf8 default NULL,
  `varlen` int(11) default NULL,
  `varvalue` varchar(50) character set utf8 default NULL,
  `keterangan` varchar(200) character set utf8 default NULL,
  `id` int(11) NOT NULL auto_increment,
  `update_status` int(11) default NULL,
  `section` varchar(50) character set utf8 default NULL,
  `category` varchar(50) character set utf8 default NULL,
  `vartype` varchar(50) character set utf8 default NULL,
  `varlist` varchar(250) character set utf8 default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=568 ;
";
if($link->query($sql))echo mysqli_error($link);
$sql="

INSERT INTO `".$cid."system_variables` (`varname`, `varlen`, `varvalue`, `keterangan`, `id`, `update_status`, `section`, `category`, `vartype`, `varlist`) VALUES
('A/R Payment Numbering', 14, '!ARP~@-~$00001', '', 1, 1, 'Purchase', 'Auto Numbering', 'String', ''),
('A/R Payment Numbering - AutoNumber', 7, '1', '', 2, 1, 'Purchase', '', '', ''),
('Admin Password', 3, 'bos', '', 5, 1, 'Inventory', 'Auto Numbering', '', ''),
('Allow Qty Stock Minus', 4, 'True', '', 6, 1, 'System', 'Auto Numbering', '', ''),
('AP Numbering', 14, '!ARP~@-~#MM~#DD~#YY~$00009', '', 7, 1, 'Purchase', 'Auto Numbering', '', ''),
('AP Numbering - AutoNumber', 7, '1', '', 8, 1, 'Purchase', 'Auto Numbering', '', ''),
('AP Payment Numbering', 14, '!APP~$00051', '', 9, 1, 'Sales', 'Auto Numbering', '', ''),
('AR Payment Numbering', 14, '!ARP~$00070', '', 10, 1, 'Sales', 'Auto Numbering', '', ''),
('AskAdminPassForExit', 5, 'False', 'NIL', 11, 1, 'Inventory', 'Auto Numbering', '', ''),
('Assembly Numbering', 14, '!ASM~@-~$00010', '', 12, 1, 'System', NULL, NULL, NULL),
('Assembly Numbering - AutoNumber', 7, '1', '', 13, 1, 'System', '', '', ''),
('AutoComplete', 5, 'True', NULL, 14, 1, 'System', NULL, NULL, NULL),
('AutoLogon', 1, '1', NULL, 15, 1, 'System', NULL, NULL, NULL),
('AutoLookUp', 4, 'True', NULL, 16, 1, 'System', NULL, NULL, NULL),
('Bersihkan Input', 1, 'True', '', 17, 1, 'Accounting', 'Auto Numbering', '', ''),
('Cetak_CreditCard', 1, '1', NULL, 18, 1, 'System', NULL, NULL, NULL),
('Cetak_LainLain', 1, '1', NULL, 19, 1, 'System', NULL, NULL, NULL),
('Cetak_PPN', 1, '1', NULL, 20, 1, 'System', NULL, NULL, NULL),
('COA Uang Muka', 4, '1209', '', 21, 1, 'Inventory', 'Auto Numbering', '', ''),
('COA Uang Muka Pembelian', 4, '1370', '', 22, 1, 'System', NULL, NULL, NULL),
('COA Uang Muka Penjualan', 4, '1370', '', 23, 1, 'System', NULL, NULL, NULL),
('CRDB SO Numbering', 15, '!CRDB~@-~$00107', '', 24, 1, 'System', NULL, NULL, NULL),
('current_org_id', 3, '000', 'struktur organisasi aktif', 25, 1, 'System', NULL, NULL, NULL),
('DisAssembly Numbering', 15, '!DASM~$00001', NULL, 26, 1, 'System', NULL, NULL, NULL),
('DisAssembly Numbering - AutoNumber', 7, '0', NULL, 27, 1, 'System', NULL, NULL, NULL),
('Display Supplier/Customer', 4, 'True', NULL, 28, 1, 'System', NULL, NULL, NULL),
('DisplayError', 1, 'True', '', 29, 1, 'System', NULL, NULL, NULL),
('Footer1', 11, 'Terimakasih', NULL, 76, 1, 'System', NULL, NULL, NULL),
('Footer2', 7, 'Footer2', NULL, 77, 1, 'System', NULL, NULL, NULL),
('Footer3', 7, 'Footer3', NULL, 78, 1, 'System', NULL, NULL, NULL),
('FormatNumeric', 14, '###,###,##0.00', NULL, 79, 1, 'System', NULL, NULL, NULL),
('GL Journal Numbering', 25, '!JU~$00004', '', 80, 1, 'Accounting', 'Auto Numbering', '', ''),
('GL Journal Numbering - AutoNumber', 1, '1', '', 81, 1, 'System', NULL, NULL, NULL),
('gstrTahunAktif', 0, '2001', NULL, 82, 1, 'System', NULL, NULL, NULL),
('Header1', 7, 'Header1', NULL, 83, 1, 'System', NULL, NULL, NULL),
('Header2', 7, 'Header2', NULL, 84, 1, 'System', NULL, NULL, NULL),
('Header3', 7, 'Header3', NULL, 85, 1, 'System', NULL, NULL, NULL),
('height', 0, '11190', NULL, 86, 1, 'System', NULL, NULL, NULL),
('Invoice DO Numbering', 14, '!JDO~$0045', '', 96, 1, 'Sales', NULL, NULL, NULL),
('Invoice DO Numbering - AutoNumber', 7, '1', '', 97, 1, 'Sales', NULL, NULL, NULL),
('Invoice Konsinyasi Numbering', 14, '!JKO~$00001', '', 98, 1, 'Sales', NULL, NULL, NULL),
('Invoice Konsinyasi Numbering - AutoNumber', 7, '1', '', 99, 1, 'Sales', NULL, NULL, NULL),
('Invoice Numbering', 14, '!PJL~$00115', '', 100, 1, 'Sales', NULL, NULL, NULL),
('Invoice Numbering - AutoNumber', 7, '1', '', 101, 1, 'Sales', NULL, NULL, NULL),
('Invoice Retur Numbering', 14, '!JRE~$00017', '', 102, 1, 'Sales', NULL, NULL, NULL),
('Invoice Retur Numbering - AutoNumber', 7, '1', '', 103, 1, 'Sales', NULL, NULL, NULL),
('Jenis_Usaha', 1, '1', 'NIL', 104, 1, 'System', NULL, NULL, NULL),
('JenisFaktur', 0, 'Invoice', NULL, 105, 1, 'Sales', NULL, NULL, NULL),
('Jumlah Discount', 1, '1', '', 106, 1, 'System', NULL, NULL, NULL),
('Konfirmasi Simpan Stock', 1, '0', NULL, 107, 1, 'System', NULL, NULL, NULL),
('Konsinyasi Numbering', 14, '!BKO~$00001', '', 108, 1, 'Sales', NULL, NULL, NULL),
('Konsinyasi Numbering - AutoNumber', 7, '1', '', 109, 1, 'Sales', NULL, NULL, NULL),
('Lady Resv Numbering', 0, '!RLD~@-~$00001', NULL, 110, 1, 'System', NULL, NULL, NULL),
('left', 0, '1650', NULL, 111, 1, 'System', NULL, NULL, NULL),
('Multi DO', 7, '0', '', 113, 1, 'Purchase', 'Auto Numbering', '', ''),
('no', 0, 'False', NULL, 114, 1, 'System', NULL, NULL, NULL),
('Pakai Discount Rupiah', 5, 'False', '', 115, 1, 'System', NULL, NULL, NULL),
('Pembelian Numbering', 14, '!PBL~$00116', '', 116, 1, 'System', NULL, NULL, NULL),
('Pembelian Numbering - AutoNumber', 7, '1', '', 117, 1, 'System', NULL, NULL, NULL),
('POS Numbering', 14, '!T8~$00019', NULL, 118, 1, 'System', NULL, NULL, NULL),
('POS Room Numbering', 14, '!POS~@-~$00016', NULL, 119, 1, 'System', NULL, NULL, NULL),
('Purchase Order Numbering', 13, '!PO~$00153', '', 120, 1, 'System', NULL, NULL, NULL),
('Purchase Order Numbering - AutoNumber', 7, '1', '', 121, 1, 'System', NULL, NULL, NULL),
('PurchaseUpdQtyWhen', 21, '1', '', 122, 1, 'System', NULL, NULL, NULL),
('Quotation Numbering', 14, '!QUT~$00001', '', 123, 1, 'Sales', NULL, NULL, NULL),
('Quotation Numbering - AutoNumber', 7, '1', '', 124, 1, 'Sales', NULL, NULL, NULL),
('Receivement Numbering', 14, '!TRM~$00248', '', 125, 1, 'System', NULL, NULL, NULL),
('Receivement Numbering - AutoNumber', 7, '1', '', 126, 1, 'System', NULL, NULL, NULL),
('Recv Finish Good Numbering', 14, '!RFG~@-~$00026', '', 127, 1, 'System', NULL, NULL, NULL),
('Reservation Numbering', 14, '!RPO~@-~$00034', NULL, 128, 1, 'System', NULL, NULL, NULL),
('Retur Beli Numbering', 14, '!BRE~$00020', '', 129, 1, 'System', NULL, NULL, NULL),
('Retur Numbering', 14, '!BRE~@-~$00018', NULL, 130, 1, 'Sales', NULL, NULL, NULL),
('Retur Numbering - AutoNumber', 7, '1', NULL, 131, 1, 'Sales', NULL, NULL, NULL),
('Room Resv Numbering', 14, '!RRN~@-~$00022', NULL, 132, 1, 'System', NULL, NULL, NULL),
('Sales Order Numbering', 13, '!SO~$00098', '', 135, 1, 'Sales', NULL, NULL, NULL),
('Sales Order Numbering - AutoNumber', 7, '1', '', 136, 1, 'Sales', NULL, NULL, NULL),
('SaleUpdQtyWhen', 21, '1 - Pengiriman Barang', '', 137, 1, 'Sales', NULL, NULL, NULL),
('Serial', 16, '0387F9FF00000686', 'NIL', 138, 1, 'System', NULL, NULL, NULL),
('SetCekStatusRoom', 5, 'False', 'NIL', 139, 1, 'System', NULL, NULL, NULL),
('SetCreditCard', 1, '0', 'NIL', 140, 1, 'System', NULL, NULL, NULL),
('SetDiscPrc', 3, '0.1', 'NIL', 141, 1, 'System', NULL, NULL, NULL),
('SetPB', 1, '0', 'NIL', 142, 1, 'System', NULL, NULL, NULL),
('SetRoundMinute', 1, '0', 'NIL', 143, 1, 'System', NULL, NULL, NULL),
('SetServiceCharge', 1, '0', 'NIL', 144, 1, 'System', NULL, NULL, NULL),
('SetShowKonsinyasi', 4, 'True', NULL, 145, 1, 'System', NULL, NULL, NULL),
('status_project', 4, 'Open', 'Status Project', 146, 1, 'System', NULL, NULL, NULL),
('status_project_1', 6, 'Closed', 'Status Project', 147, 1, 'System', NULL, NULL, NULL),
('Stock Receive Numbering', 14, '!RCV~@-~$00024', NULL, 148, 1, 'System', NULL, NULL, NULL),
('strCompany', 0, 'ATL', NULL, 149, 1, 'System', NULL, NULL, NULL),
('strCurrentModule', 0, 'frmMain', NULL, 150, 1, 'System', NULL, NULL, NULL),
('Tampil Harga Beli', 1, '0', '', 151, 1, 'System', NULL, NULL, NULL),
('Tampil History Harga', 1, '', '', 152, 1, 'System', NULL, NULL, NULL),
('Tampil Multi Pricing', 1, '', '', 153, 1, 'System', NULL, NULL, NULL),
('top', 0, '165', NULL, 154, 1, 'System', NULL, NULL, NULL),
('TRX OE Numbering', 0, '!TRX~$00004', NULL, 155, 1, 'System', NULL, NULL, NULL),
('txtPassword', 0, 'ADMIN', NULL, 156, 1, 'System', NULL, NULL, NULL),
('txtUsername', 0, 'administrator', NULL, 157, 1, 'System', NULL, NULL, NULL),
('Ubah Qty Assembly DisAssembly', 4, 'True', '', 158, 1, 'System', NULL, NULL, NULL),
('Update AR/AP Balance in Bank Module', 5, 'False', NULL, 159, 1, 'System', NULL, NULL, NULL),
('Use Stock Receipt', 1, '0', 'NIL', 160, 1, 'System', NULL, NULL, NULL),
('width', 0, '15480', NULL, 161, 1, 'System', NULL, NULL, NULL),
('WindowState', 1, '2', NULL, 162, 1, 'System', NULL, NULL, NULL),
('Work Order Numbering', 13, '!WO~@-~$00013', NULL, 163, 1, 'System', NULL, NULL, NULL),
('yes', 0, 'True', NULL, 164, 1, 'System', NULL, NULL, NULL),
('DefaultCurrency', 3, 'IDR', '', 175, 1, 'System', NULL, NULL, NULL),
('BeginDate', 10, '2012-01-01 00:00', '', 176, 1, 'System', NULL, NULL, NULL),
('FiscalYear', 10, '2012', '', 177, 1, 'System', NULL, NULL, NULL),
('AllowInputDateFrom', 10, '2012-01-01 00:00', '', 178, 1, 'System', 'Auto Numbering', '', ''),
('AllowInputDateTo', 10, '2012-12-31 00:00', '', 179, 1, 'Purchase', 'Auto Numbering', '', ''),
('ShowReminder', 4, 'True', '', 180, 1, 'System', NULL, NULL, NULL),
('ShowTips', 4, 'FALSE', 'Show Tips', 181, 1, 'System', NULL, NULL, NULL),
('PO Jumlah Discount', 1, '1', '', 206, NULL, 'System', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Simple', 'Jenis faktur', 211, NULL, 'Sales', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Profesional', 'Jenis faktur', 212, NULL, 'Sales', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Product Detail', 'Jenis faktur', 213, NULL, 'Sales', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Service', 'Jenis faktur', 214, NULL, 'Sales', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Konsinyasi', 'Jenis faktur', 215, NULL, 'Sales', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Faktur Eceran', 'Jenis faktur', 216, NULL, 'Sales', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Faktur Grosir', 'Jenis faktur', 217, NULL, 'Sales', NULL, NULL, NULL),
('AppSecureLevel', 1, '0', 'NIL', 219, NULL, 'Sales', 'Auto Numbering', '', ''),
('HargaBeliPoItem', 1, '0', '', 220, NULL, 'System', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Faktur Pangan', 'Jenis faktur', 222, NULL, 'Sales', NULL, NULL, NULL),
('TypeOfInvoice', 0, 'Faktur Kebun', 'Jenis faktur', 223, NULL, 'Sales', NULL, NULL, NULL),
('PO Request Numbering', 14, '!POR~@-~$00001', 'NIL', 225, NULL, 'System', NULL, NULL, NULL),
('AR Payment Numbering - AutoNumber', 1, '1', '', 232, NULL, 'System', NULL, NULL, NULL),
('Acc In KAS Numbering', 15, '!KM.KAS.~$00072', '', 233, NULL, 'Banking', 'Auto Numbering', '', ''),
('Acc Out KAS Numbering', 15, '!KK.KAS.~$00056', '', 234, NULL, 'Sales', 'Auto Numbering', '', ''),
('Retur Beli Numbering - AutoNumber', 1, '1', '', 236, NULL, 'System', NULL, NULL, NULL),
('AP Payment Numbering - AutoNumber', 1, '1', '', 237, NULL, 'Purchase', 'Auto Numbering', '', ''),
('Inventory Numbering - AutoNumber', 1, '1', '', 238, NULL, 'Inventory', NULL, NULL, NULL),
('Inventory Numbering', 6, '$00013', '', 239, NULL, 'Inventory', NULL, NULL, NULL),
('TerbilangInvoice', 1, '0', '', 257, NULL, 'System', NULL, NULL, NULL),
('SelectRecWhenPrintInvoice', 1, '0', '', 259, NULL, 'Sales', NULL, NULL, NULL),
('FingerprintKey', 1, 'UAA2ARPPEAEJEEE66', 'FingerprintKey', 268, NULL, 'System', NULL, NULL, NULL),
('LicenceKey', 37, 'HI42T2GP7EIMN3A2AAA13AE7IEE68IIA2EIAA', 'NIL', 269, NULL, 'System', NULL, NULL, NULL),
('LicenceCount', 1, '2', 'NIL', 270, NULL, 'System', NULL, NULL, NULL),
('LicenseKey', 1, 'HAA2A2BPE4EJ6EE66', 'LicenseKey', 271, NULL, 'System', NULL, NULL, NULL),
('LicenseCount', 1, '2', 'LicenseCount', 272, NULL, 'System', NULL, NULL, NULL),
('AppLicenseStatus', 1, '1', 'NIL', 273, NULL, 'Sales', 'Auto Numbering', '', ''),
('Acc In BCA Numbering', 15, '!BCA.KM.~$00035', '', 275, NULL, 'Banking', 'Auto Numbering', '', ''),
('Acc Out BCA Numbering', 15, '!BCA.KK.~$00015', '', 276, NULL, 'Banking', 'Auto Numbering', '', ''),
('MultiCurrency', 1, '1', 'NIL', 277, NULL, 'System', '', '', ''),
('MultiWarehouse', 1, '1', 'NIL', 278, NULL, 'System', '', '', ''),
('MultiBranch', 1, '1', 'NIL', 279, NULL, 'System', NULL, NULL, NULL),
('MultiCustomerBranch', 1, '1', 'NIL', 281, NULL, NULL, NULL, NULL, NULL),
('DefaultGudang', 6, 'Gudang', 'NIL', 282, NULL, NULL, NULL, NULL, NULL),
('DefaultCurrencyRate', 1, '1', 'Default Currency Rate', 283, NULL, NULL, NULL, NULL, NULL),
('Invoice Angkutan Numbering', 7, '$000016', 'NIL', 284, NULL, NULL, NULL, NULL, NULL),
('Biaya Angkutan Numbering', 11, '@BA~$000032', 'NIL', 285, NULL, NULL, NULL, NULL, NULL),
('ReCalcHppBeforeJournal', 1, '0', 'NIL', 286, NULL, NULL, NULL, NULL, NULL),
('AutoCreateSupplierWhenOrder', 1, 'True', '', 295, NULL, NULL, NULL, NULL, NULL),
('AllowMoveToNextControlWhenEmpty', 1, '', '', 296, NULL, NULL, NULL, NULL, NULL),
('Multi Currency', 1, 'True', '', 297, NULL, NULL, NULL, NULL, NULL),
('AutoCreateCustomerWhenOrder', 1, '1', '', 298, NULL, NULL, NULL, NULL, NULL),
('GridAutoCompletion', 1, '1', '', 299, NULL, NULL, NULL, NULL, NULL),
('GridAutoDropdown', 1, '1', '', 300, NULL, NULL, NULL, NULL, NULL),
('GridMoveColWithTab', 1, '0', '', 301, NULL, NULL, NULL, NULL, NULL),
('Service Order Numbering', 14, '!SRV~@-~$00003', 'service job numbering', 313, NULL, NULL, NULL, NULL, NULL),
('Service job numbering', 15, '!SJOB~@-~$00005', 'service job numbering', 314, NULL, NULL, NULL, NULL, NULL),
('NilaiPembulatan', 3, '0', 'nil', 315, NULL, NULL, NULL, NULL, NULL),
('adjust_raw_material', 5, 'True', 'nil', 322, NULL, NULL, NULL, NULL, NULL),
('recalc_discount_when_report', 5, 'False', 'nil', 325, NULL, NULL, NULL, NULL, NULL),
('Customer ShipTo Numbering', 6, '$00008', 'nil', 327, NULL, NULL, NULL, NULL, NULL),
('Invoice Numbering - Locked', 1, '1', '', 329, NULL, NULL, NULL, NULL, NULL),
('GabungKodeJurnal', 1, '1', '', 330, NULL, NULL, NULL, NULL, NULL),
('LoadSelectItem', 1, '', '', 331, NULL, NULL, NULL, NULL, NULL),
('ar_payment_date_locked', 1, '', '', 332, NULL, NULL, NULL, NULL, NULL),
('allow_reprint_do', 1, '', '', 333, NULL, NULL, NULL, NULL, NULL),
('allow_reprint_invoice', 1, '0', '', 334, NULL, NULL, NULL, NULL, NULL),
('allow_reprint_so', 1, '1', 'NIL', 335, NULL, NULL, NULL, NULL, NULL),
('allow_reprint_retur_jual', 1, '1', 'NIL', 336, NULL, NULL, NULL, NULL, NULL),
('allow_reprint_po', 1, '1', 'NIL', 337, NULL, NULL, NULL, NULL, NULL),
('allow_reprint_po_invoice', 1, '1', 'NIL', 338, NULL, NULL, NULL, NULL, NULL),
('allow_reprint_retur_beli', 1, '1', 'NIL', 339, NULL, NULL, NULL, NULL, NULL),
('lock_change_item', 5, 'True', 'nil', 343, NULL, NULL, NULL, NULL, NULL),
('Adjustment Numbering', 11, '!ADJ~$00020', '', 345, NULL, NULL, NULL, NULL, NULL),
('Transfer Stock Numbering', 14, '!TRX~$00002', '', 348, NULL, NULL, NULL, NULL, NULL),
('Adjustment Numbering - AutoNumber', 1, '1', '', 349, NULL, NULL, NULL, NULL, NULL),
('Transfer Stock Numbering - AutoNumber', 1, '0', 'NIL', 350, NULL, NULL, NULL, NULL, NULL),
('col_width_kode', 4, '3110', 'nil', 353, NULL, NULL, NULL, NULL, NULL),
('col_width_qty', 3, '555', 'nil', 354, NULL, NULL, NULL, NULL, NULL),
('col_width_unit', 3, '450', 'nil', 355, NULL, NULL, NULL, NULL, NULL),
('col_width_harga', 4, '1005', 'nil', 356, NULL, NULL, NULL, NULL, NULL),
('col_width_disc_prc', 3, '615', 'nil', 357, NULL, NULL, NULL, NULL, NULL),
('col_width_disc_amt', 3, '700', 'nil', 358, NULL, NULL, NULL, NULL, NULL),
('col_width_jumlah', 4, '1500', 'nil', 359, NULL, NULL, NULL, NULL, NULL),
('Acc In LIPO 234 Numbering', 11, '!KML~$00001', 'NIL', 365, NULL, NULL, NULL, NULL, NULL),
('Acc OutLIPO 234 Numbering', 11, '!KKL~$00002', 'NIL', 366, NULL, NULL, NULL, NULL, NULL),
('NextShipToId', 12, '!SHT1~$00008', 'Penomoran untuk kode pengiriman customer', 371, NULL, NULL, NULL, NULL, NULL),
('AllowChangePrice', 0, 'true', NULL, 372, NULL, NULL, NULL, NULL, NULL),
('AllowChangeDiscItem', 0, 'true', NULL, 373, NULL, NULL, NULL, NULL, NULL),
('allow_cashier_report', 4, 'True', 'nil', 376, NULL, NULL, NULL, NULL, NULL),
('LockSO_Freight', 0, 'true', NULL, 377, NULL, NULL, NULL, NULL, NULL),
('LockSO_Tax', 0, 'true', NULL, 378, NULL, NULL, NULL, NULL, NULL),
('DisplayConfirmWhenPayment', 0, 'false', NULL, 379, NULL, NULL, NULL, NULL, NULL),
('ItemReturBased', 1, '2', 'NIL', 387, NULL, NULL, NULL, NULL, NULL),
('AskGLIDPosting', 5, 'False', 'NIL', 394, NULL, NULL, NULL, NULL, NULL),
('Acc In Mandiri Numbering', 12, '!BMM.~$00002', 'NIL', 395, NULL, NULL, NULL, NULL, NULL),
('Acc OutMandiri Numbering', 12, '!BKM.~$00002', 'NIL', 396, NULL, NULL, NULL, NULL, NULL),
('Invoice DO Other Numbering - AutoNumber', 1, '1', '', 397, NULL, NULL, NULL, NULL, NULL),
('Invoice DO Other Numbering', 11, '!JDL~$00017', '', 398, NULL, NULL, NULL, NULL, NULL),
('Invoice DO Other Numbering - Locked', 1, '1', '', 399, NULL, NULL, NULL, NULL, NULL),
('tmp_no_po', 7, 'JDO0037', '', 400, NULL, NULL, NULL, NULL, NULL),
('tmp_no_so', 7, 'JDO0037', 'SO00033', 401, NULL, NULL, NULL, NULL, NULL),
('HideAccountEarningAccount', 5, 'True', '', 415, NULL, NULL, NULL, NULL, NULL),
('AllowVoucherNonMember', 5, 'True', 'nil', 416, NULL, NULL, NULL, NULL, NULL),
('MoveToNextCol', 5, 'False', 'NIL', 418, NULL, NULL, NULL, NULL, NULL),
('InvalidAcc_Jurnal', 0, '1483', 'InvalidAcc_Jurnal', 419, NULL, NULL, NULL, NULL, NULL),
('InvalidAcc_Jurnal', 0, '1408', 'InvalidAcc_Jurnal', 420, NULL, NULL, NULL, NULL, NULL),
('IncPoAutoNumWhenEdit', 0, 'true', NULL, 421, NULL, NULL, NULL, NULL, NULL),
('UnlockChangePriceInvoice', 5, '', '', 422, NULL, NULL, NULL, NULL, NULL),
('ProtectChangePrice', 5, '', '', 423, NULL, NULL, NULL, NULL, NULL),
('ProtectChangeDisc', 5, '', '', 424, NULL, NULL, NULL, NULL, NULL),
('Purchase Order Number', 21, '', 'No Comment', 445, NULL, NULL, NULL, NULL, NULL),
('Retur Jual Numbering', 20, '', 'No Comment', 446, NULL, NULL, NULL, NULL, NULL),
('Adjustmnet Numbering', 20, '', 'No Comment', 447, NULL, NULL, NULL, NULL, NULL),
('Other Delivery Numbering', 24, '!DOX~$00012', 'No Comment', 448, NULL, NULL, NULL, NULL, NULL),
('Retur Pembelian Numbering', 25, '!PR~$00028', 'No Comment', 449, NULL, NULL, NULL, NULL, NULL),
('Delivery Order Numbering', 24, '!SJ~$00039', 'No Comment', 450, NULL, NULL, NULL, NULL, NULL),
('Retur Invoice Numbering', 23, '', 'No Comment', 452, NULL, NULL, NULL, NULL, NULL),
('CRDB PO Numbering', 17, '!CRDB.PO.~@-~$00001', 'No Comment', 453, NULL, NULL, NULL, NULL, NULL),
('Voucher in Numbering', 20, '', 'No Comment', 454, NULL, NULL, NULL, NULL, NULL),
('Acc In  Numbering', 17, '', 'No Comment', 455, NULL, NULL, NULL, NULL, NULL),
('Acc In BCW Numbering', 20, '', 'No Comment', 456, NULL, NULL, NULL, NULL, NULL),
('Voucher  Numbering', 18, '', 'No Comment', 457, NULL, NULL, NULL, NULL, NULL),
('Voucher out Numbering', 21, '', 'No Comment', 458, NULL, NULL, NULL, NULL, NULL),
('Acc Out  Numbering', 18, '', 'No Comment', 460, NULL, NULL, NULL, NULL, NULL),
('Invoice Kontan Numbering', 24, '!FK~$00003', 'Faktur Jual Kontan', 475, NULL, NULL, NULL, NULL, NULL),
('', 0, '!TRP~$00001', 'Penerimaan PO', 489, NULL, NULL, NULL, NULL, NULL),
('PO Receive Numbering', 20, '!TRP~$00038', 'Penerimaan PO', 490, NULL, NULL, NULL, NULL, NULL),
('SalQtyDec', 9, '2', 'No Comment', 491, NULL, NULL, NULL, NULL, NULL),
('SalPriDec', 9, '0', 'No Comment', 492, NULL, NULL, NULL, NULL, NULL),
('InvQtyDec', 9, '2', 'No Comment', 493, NULL, NULL, NULL, NULL, NULL),
('InvPriDec', 9, '0', 'No Comment', 494, NULL, NULL, NULL, NULL, NULL),
('PurQtyDec', 9, '2', 'No Comment', 495, NULL, NULL, NULL, NULL, NULL),
('PurPriDec', 9, '0', 'No Comment', 496, NULL, NULL, NULL, NULL, NULL),
('DiscRupiah', 10, 'True', 'No Comment', 497, NULL, NULL, NULL, NULL, NULL),
('UseGiroGantung', 14, '1', 'No Comment', 498, NULL, NULL, NULL, NULL, NULL),
('AllowPayMinus', 13, '1', 'No Comment', 499, NULL, NULL, NULL, NULL, NULL),
('CR Debit Numbering', NULL, '!DBSO~@-~$00001', NULL, 500, NULL, NULL, NULL, NULL, NULL),
('ContactOnSales', NULL, 'Purchasing', NULL, 501, NULL, NULL, NULL, NULL, NULL),
('Default Invoice Type', NULL, 'Simple', NULL, 502, NULL, NULL, NULL, NULL, NULL),
('Freight Taxable', NULL, 'True', NULL, 503, NULL, NULL, NULL, NULL, NULL),
('Other Taxable', NULL, 'True', NULL, 504, NULL, NULL, NULL, NULL, NULL),
('Undeposited Checks', NULL, 'True', NULL, 505, NULL, NULL, NULL, NULL, NULL),
('show_kas', NULL, 'True', NULL, 506, NULL, NULL, NULL, NULL, NULL),
('so_number', 9, '!SO~$00052', 'No Comment', 507, NULL, NULL, NULL, NULL, NULL),
('faktur_number', 13, '!PJL~$00074', 'No Comment', 508, NULL, NULL, NULL, NULL, NULL),
('do_number', 9, '!JDO~$0044', 'No Comment', 509, NULL, NULL, NULL, NULL, NULL),
('konsinyasi_number', 17, '!JKO~$00001', 'No Comment', 510, NULL, NULL, NULL, NULL, NULL),
('retur_number', 12, '!JRE~$00015', 'No Comment', 511, NULL, NULL, NULL, NULL, NULL),
('payment_number', 14, '!ARP~$00030', 'No Comment', 512, NULL, NULL, NULL, NULL, NULL),
('quot_number', 11, '!QUT~$00001', 'No Comment', 513, NULL, NULL, NULL, NULL, NULL),
('stock_send_number', 17, '!DOX~$00007', 'No Comment', 514, NULL, NULL, NULL, NULL, NULL),
('credit_memo_number', 18, '!CRDB~@-~$00107', 'No Comment', 515, NULL, NULL, NULL, NULL, NULL),
('debit_memo_number', 17, '!DBSO~@-~$00001', 'No Comment', 516, NULL, NULL, NULL, NULL, NULL),
('fakur_pajak_number', 18, '', 'No Comment', 517, NULL, NULL, NULL, NULL, NULL),
('discount_bertingkat', 19, '1', 'No Comment', 518, NULL, NULL, NULL, NULL, NULL),
('nama_di_faktur', 14, 'Andri', 'No Comment', 519, NULL, NULL, NULL, NULL, NULL),
('CR PO Numbering', 15, 'CRPO~$00001', 'No Comment', 520, NULL, NULL, NULL, NULL, NULL),
('DB PO Numbering', 15, '!DBPO~$00001', 'No Comment', 521, NULL, NULL, NULL, NULL, NULL),
('Purchase Order Contact', 22, 'Purchasing', 'No Comment', 522, NULL, NULL, NULL, NULL, NULL),
('POItemDisplay', 13, '0', 'No Comment', 523, NULL, NULL, NULL, NULL, NULL),
('PO Show Items', 13, '0', 'No Comment', 524, NULL, NULL, NULL, NULL, NULL),
('Inventory Costing', 17, '0', 'No Comment', 525, NULL, NULL, NULL, NULL, NULL),
('Perpetual Inventory', 19, '0', 'No Comment', 526, NULL, NULL, NULL, NULL, NULL),
('Display ShipTos', 15, '0', 'No Comment', 527, NULL, NULL, NULL, NULL, NULL),
('customer order', 14, '0', 'No Comment', 528, NULL, NULL, NULL, NULL, NULL),
('InventorySearch', 15, '0', 'No Comment', 529, NULL, NULL, NULL, NULL, NULL),
('customer numbering', 18, '0', 'No Comment', 530, NULL, NULL, NULL, NULL, NULL),
('Supplier Numbering', 18, '0', 'No Comment', 531, NULL, NULL, NULL, NULL, NULL),
('button_position', 15, '0', 'No Comment', 532, NULL, NULL, NULL, NULL, NULL),
('C01 Invoice Numbering', NULL, '!P-C01~$00006', 'Numbering', 533, NULL, NULL, NULL, NULL, NULL),
(' Invoice Numbering', NULL, '!P-~$00001', 'Numbering', 534, NULL, NULL, NULL, NULL, NULL),
('T01 Invoice Numbering', NULL, '!P-T01~$00006', 'Numbering', 535, NULL, NULL, NULL, NULL, NULL),
('T01 Receive Numbering', NULL, '!R-T01~$00010', 'Numbering', 536, NULL, NULL, NULL, NULL, NULL),
('C01 Receive Numbering', NULL, '!R-C01~$00010', 'Numbering', 537, NULL, NULL, NULL, NULL, NULL),
('C01 Delivery Numbering', NULL, '!D-C01~$00009', 'Numbering', 538, NULL, NULL, NULL, NULL, NULL),
('C01 AR Payment Numbering', NULL, '!ARP-C01~$00006', 'Numbering', 539, NULL, NULL, NULL, NULL, NULL),
('C01 Adjust Numbering', NULL, '!ADJ-C01~$00004', 'Numbering', 540, NULL, NULL, NULL, NULL, NULL),
('C01 Pembelian Numbering', NULL, '!FBC01~$00011', 'Numbering', 541, NULL, NULL, NULL, NULL, NULL),
('C01 AP Payment Numbering', NULL, '!APP-C01~$00006', 'Numbering', 542, NULL, NULL, NULL, NULL, NULL),
('Flag [Customers] add sc exempt', 1, '1', 'nil', 543, NULL, NULL, NULL, NULL, NULL),
('Flag [Invoice lineitems] change field type', 1, '1', 'nil', 544, NULL, NULL, NULL, NULL, NULL),
('Purchase Invoice Numbering', NULL, '!PI~$00005', 'Numbering', 545, NULL, NULL, NULL, NULL, NULL),
('Retur Pembelian Numbering', NULL, '!PR~$00028', 'Numbering', 546, NULL, NULL, NULL, NULL, NULL),
('Delivery Order Numbering', NULL, '!SJ~$00039', 'Numbering', 547, NULL, NULL, NULL, NULL, NULL),
('CrDB Numbering', NULL, '!CRDB~$00003', 'Numbering', 548, NULL, NULL, NULL, NULL, NULL),
('Other Recievement Numbering', NULL, '!EIN~$00003', 'Numbering', 549, NULL, NULL, NULL, NULL, NULL),
('Other Receivement Numbering', NULL, '!EIN~$00007', 'Numbering', 550, NULL, NULL, NULL, NULL, NULL),
('COA Retur Penjualan', NULL, '1504', 'auto', 558, NULL, NULL, NULL, NULL, NULL),
('COA Retur Penjualan', NULL, '1504', 'auto', 559, NULL, NULL, NULL, NULL, NULL),
('COA Item Out Others', NULL, '1434', 'auto', 560, NULL, NULL, NULL, NULL, NULL),
('COA Item In Others', NULL, '1434', 'auto', 561, NULL, NULL, NULL, NULL, NULL),
('COA Item Adjustment', NULL, '1434', 'auto', 562, NULL, NULL, NULL, NULL, NULL),
('CoaChargeCreditCard', NULL, '0', 'auto', 563, NULL, NULL, NULL, NULL, NULL),
('CoaPromo', NULL, '0', 'auto', 564, NULL, NULL, NULL, NULL, NULL),
('CoaGift', NULL, '0', 'auto', 565, NULL, NULL, NULL, NULL, NULL),
('Adjust Numbering', NULL, '!ADJ~$00006', 'Numbering', 567, NULL, NULL, NULL, NULL, NULL);
";
if($link->query($sql))echo mysqli_error($link);	
	?>